#! /usr/bin/env python3
# vim:fenc=utf-8
#
# Copyright © 2026 David Lilien <dlilien@iu.edu>
#
"""
Load data for the Greenland inversions.

This creates the HDF5 files that are used by the inversions. It makes things a
little bit faster to run the inversions with different parameters since the
data loads can be pretty slow.

Usage:
    load_data.py --data-dir <data_dir> --mesh-dir <mesh_dir>

    load_data.py --help
"""

import argparse
import sys
from pathlib import Path

import cartopy.crs as ccrs
import numpy as np
import rasterio
import xarray as xr
from pyproj import Transformer
from scipy.interpolate import LinearNDInterpolator, NearestNDInterpolator


nps = ccrs.Stereographic(
    central_latitude=90.0, central_longitude=-45.0, true_scale_latitude=70
)


DEFAULT_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
DEFAULT_MESH_DIR = Path(__file__).resolve().parent.parent / "meshes"
DEFAULT_FIG_DIR = Path(__file__).resolve().parent.parent / "figs" / "loading"
OUTLINE_KINDS = ("promice", "simple", "detailed", "buffered")


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Load Greenland data onto generated meshes."
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=DEFAULT_DATA_DIR,
        help="Directory containing data downloaded by download_data.py.",
    )
    parser.add_argument(
        "--mesh-dir",
        type=Path,
        default=DEFAULT_MESH_DIR,
        help="Directory containing meshes generated by mesh_greenland.py.",
    )
    parser.add_argument(
        "--outline-kind",
        choices=OUTLINE_KINDS,
        nargs="+",
        default=OUTLINE_KINDS,
        help="Mesh outline kind(s) to process.",
    )
    parser.add_argument(
        "--min-lc",
        type=int,
        default=250,
        help="Smallest fine target length scale.",
    )
    parser.add_argument(
        "--num-levels",
        type=int,
        default=8,
        help="Number of mesh resolution levels to process.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing checkpoint files.",
    )
    parser.add_argument(
        "--save-plots",
        action="store_true",
        help="Save tripcolor plots for the lowest resolution mesh of each type.",
    )
    parser.add_argument(
        "--fig-dir",
        type=Path,
        default=DEFAULT_FIG_DIR,
        help="Directory for loading diagnostic plots.",
    )
    return parser.parse_args()


def data_paths(data_dir):
    """Build input data paths from the download_data.py directory layout."""
    bedmachine_fn = data_dir / "bedmachine" / "BedMachineGreenland-v6.nc"
    racmo_fn = (
        data_dir
        / "racmo"
        / "GRN11_RACMO24p1_data"
        / "smbgl_monthlyS_GRN11_RACMO24p1_200601_201512.nc"
    )
    velocity_dir = data_dir / "velocity" / "multiyear"
    vx_fn = velocity_dir / "greenland_vel_mosaic250_vx_v1.tif"
    vy_fn = velocity_dir / "greenland_vel_mosaic250_vy_v1.tif"
    ex_fn = velocity_dir / "greenland_vel_mosaic250_ex_v1.tif"
    ey_fn = velocity_dir / "greenland_vel_mosaic250_ey_v1.tif"

    for path in (bedmachine_fn, racmo_fn, vx_fn, vy_fn, ex_fn, ey_fn):
        if not path.exists():
            raise FileNotFoundError(path)

    return {
        "smb": racmo_fn,
        "bed": f"netcdf:{bedmachine_fn}:bed",
        "thickness": f"netcdf:{bedmachine_fn}:thickness",
        "vx": vx_fn,
        "vy": vy_fn,
        "ex": ex_fn,
        "ey": ey_fn,
    }


def iter_mesh_paths(mesh_dir, outline_kinds, min_lc, num_levels):
    """Yield mesh and output checkpoint paths using mesh_greenland.py names."""
    for outline_kind in outline_kinds:
        for lc in [min_lc * 2**i for i in range(num_levels)]:
            rough_targ = 10 * lc
            stem = f"greenland_{outline_kind}_{rough_targ}_{lc}"
            yield outline_kind, lc, mesh_dir / f"{stem}.msh", mesh_dir / f"{stem}.h5"


def load_racmo_smb(path):
    """Load RACMO SMB with xarray and average over time."""
    data = xr.open_dataset(path)["smbgl"].mean("time")
    if "height" in data.dims:
        data = data.squeeze("height", drop=True)
    return data


def interpolate_racmo_smb(smb_data, Q, fd):
    """Interpolate RACMO SMB from lon/lat coordinates to a Firedrake space."""
    transformer = Transformer.from_crs("EPSG:4326", "EPSG:3413", always_xy=True)
    x, y = transformer.transform(smb_data.lon.values, smb_data.lat.values)

    values = smb_data.values
    valid = np.isfinite(values)
    points = np.column_stack((x[valid], y[valid]))
    data = values[valid]

    mesh = Q.mesh()
    element = Q.ufl_element()
    V = fd.VectorFunctionSpace(mesh, element)
    coords = fd.Function(V).interpolate(mesh.coordinates).dat.data_ro[:, :2]

    linear = LinearNDInterpolator(points, data, fill_value=np.nan)
    sampled = linear(coords[:, 0], coords[:, 1])

    missing = ~np.isfinite(sampled)
    if np.any(missing):
        nearest = NearestNDInterpolator(points, data)
        sampled[missing] = nearest(coords[missing, 0], coords[missing, 1])

    smb = fd.Function(Q)
    smb.dat.data[:] = np.maximum(sampled, 0.0)
    return smb


def replace_velocity_nodata(function, fillvalue, threshold=2.0e4):
    """Replace MEaSUREs velocity no-data sentinels in a Firedrake function."""
    values = function.dat.data[:]
    bad = (~np.isfinite(values)) | (np.abs(values) > threshold)
    values[bad] = fillvalue


def save_loading_plots(fields, mesh2d, outline_kind, lc, fig_dir, fd):
    """Save tripcolor plots for fields loaded onto a mesh."""
    import matplotlib.pyplot as plt

    fig_dir.mkdir(parents=True, exist_ok=True)
    plot_fields = {
        "u_x": (fields["u"].sub(0), -1000, 1000, "PuOr", "m yr$^{-1}$"),
        "u_y": (fields["u"].sub(1), -1000, 1000, "PuOr", "m yr$^{-1}$"),
        "speed": (fields["speed"], 0, 2000, "viridis", "m yr$^{-1}$"),
        "sigma_u_x": (fields["sigma_u"].sub(0), 0, 100, "Reds", "m yr$^{-1}$"),
        "sigma_u_y": (fields["sigma_u"].sub(1), -0, 100, "Reds", "m yr$^{-1}$"),
        "smb": (fields["smb"], -200, 200, "bwr_r", "mm yr$^{-1}$"),
        "H": (fields["H"], 0, 3000, "viridis", "m"),
        "b": (fields["b"], -1000, 1000, "PiYG", "m"),
    }

    for name, stuff in plot_fields.items():
        source, vmin, vmax, cmap, label = stuff

        fig, ax = plt.subplots(figsize=(6, 9), subplot_kw={"projection": nps})
        ax.coastlines()
        colors = fd.tripcolor(source, axes=ax, vmin=vmin, vmax=vmax, cmap=cmap, transform=ccrs.epsg(3413))
        fig.colorbar(colors, ax=ax, shrink=0.8, label=label)
        ax.set_title(f"{outline_kind} lc={lc}: {name}")
        ax.set_extent([-6e5, 8e5, -3.5e6, -0.75e6], crs=nps)
        ax.gridlines(draw_labels=["left", "top"], x_inline=False, y_inline=False)
        fig.savefig(fig_dir / f"greenland_{outline_kind}_{lc}_{name}.png", dpi=200)
        plt.close(fig)


def main():
    """Load Greenland datasets onto generated meshes from command-line arguments."""
    args = parse_args()
    sys.argv = [sys.argv[0]]

    import firedrake as fd
    import icepack

    data_dir = args.data_dir.expanduser()
    mesh_dir = args.mesh_dir.expanduser()
    fig_dir = args.fig_dir.expanduser()
    paths = data_paths(data_dir)

    vx = rasterio.open(paths["vx"], masked=True)
    vy = rasterio.open(paths["vy"], masked=True)
    ex = rasterio.open(paths["ex"], masked=True)
    ey = rasterio.open(paths["ey"], masked=True)
    
    smb_data = load_racmo_smb(paths["smb"])
    thick_arr = rasterio.open(paths["thickness"])

    bed_arr = rasterio.open(paths["bed"])

    for outline_kind, lc, mesh_fn, out_fn in iter_mesh_paths(
        mesh_dir, args.outline_kind, args.min_lc, args.num_levels
    ):
        if not mesh_fn.exists():
            print(f"Skipping missing mesh: {mesh_fn}")
            continue
        if out_fn.exists() and not args.overwrite:
            print(f"Skipping existing output: {out_fn}")
            continue

        print(f"Doing {mesh_fn.name}...")
        mesh2d = fd.Mesh(str(mesh_fn))
        mesh2d.name = "greenland_2d"
        mesh3d = fd.ExtrudedMesh(mesh2d, layers=1)
        mesh3d.name = "greenland_3d"

        V3d = fd.VectorFunctionSpace(mesh3d, "CG", 1, dim=2, vfamily="R", vdegree=0)
        Q3d = fd.FunctionSpace(mesh3d, "CG", 1, vfamily="R", vdegree=0)

        V2d = fd.VectorFunctionSpace(mesh2d, "CG", 1, dim=2, vfamily="R", vdegree=0)
        Q2d = fd.FunctionSpace(mesh2d, "CG", 1, vfamily="R", vdegree=0)

        for mesh, V, Q, suffix in [(mesh2d, V2d, Q2d, "_2d"),
                                   (mesh3d, V3d, Q3d, "_3d")]:
            smb = interpolate_racmo_smb(smb_data, Q, fd)
            u = icepack.interpolate(
                (vx, vy),
                V,
                fillvalue=0.0,
            )
            replace_velocity_nodata(u, 0.0)
            sigma_u = icepack.interpolate(
                (ex, ey),
                V,
                fillvalue=1.04,
            )
            replace_velocity_nodata(sigma_u, 1.0e4)
            H = fd.Function(Q).interpolate(
                fd.max_value(icepack.interpolate(thick_arr, Q), fd.Constant(10.0))
            )
            b = icepack.interpolate(bed_arr, Q)
            speed = fd.Function(Q).interpolate(fd.sqrt(fd.inner(u, u)))

            if args.save_plots and suffix == "_2d":
                save_loading_plots(
                    {
                        "u": u,
                        "sigma_u": sigma_u,
                        "speed": speed,
                        "smb": smb,
                        "H": H,
                        "b": b,
                    },
                    mesh2d,
                    outline_kind,
                    lc,
                    fig_dir,
                    fd,
                )

            with fd.CheckpointFile(str(out_fn), "w") as chk:
                chk.save_mesh(mesh)
                chk.save_function(u, name="u" + suffix)
                chk.save_function(sigma_u, name="sigma_u" + suffix)
                chk.save_function(smb, name="smb" + suffix)
                chk.save_function(H, name="H" + suffix)
                chk.save_function(b, name="b" + suffix)


if __name__ == "__main__":
    main()
