#!/usr/bin/env python3
"""
Generate the boundary-id sidecars from a generated Antarctica .msh file.

The mesh pipeline (mesh_antarctica.py / icepack2_tools.mesh) tags each
boundary segment as a gmsh physical group named "Calving_N" or "Other_N",
and the ice surface as "Ice". In gmsh's MSH 2.2 format the physical-group
tag is exactly the integer boundary marker that Firedrake exposes, so the
downstream solvers' boundary_ids.json is just that name->tag map binned
into calving-front vs. other (land/grounding) boundaries:

    {"calving": [<tags>], "other": [<tags>]}

Two files are written: the per-mesh boundary_ids_<mesh stem>.json that every
solver prefers (icepack2_tools/boundary.py), and the shared boundary_ids.json
fallback. The per-mesh name is what makes a stale sidecar impossible to pick up
by accident - a second mesh build overwrites the shared file but not the one
belonging to the mesh a run is actually using.

Usage:
    python scripts/make_boundary_ids.py
    ISMIP7_MESH=path/to/mesh.msh python scripts/make_boundary_ids.py
    ISMIP7_BNDIDS=out.json python scripts/make_boundary_ids.py   # single file
"""

import json
import os
import re

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MESH_DIR = os.path.join(_ROOT, "mesh")

lc = int(os.environ.get("ISMIP7_LC", "2500"))
lc_coarse = int(os.environ.get("ISMIP7_LC_COARSE", "64000"))


def parse_physical_names(mesh_fn):
    """Return list of (dim, tag, name) from a MSH file's $PhysicalNames block."""
    entries = []
    with open(mesh_fn) as f:
        in_block = False
        for line in f:
            line = line.strip()
            if line == "$PhysicalNames":
                in_block = True
                next(f)  # skip the count line
                continue
            if line == "$EndPhysicalNames":
                break
            if in_block:
                m = re.match(r'(\d+)\s+(\d+)\s+"(.*)"', line)
                if m:
                    entries.append((int(m.group(1)), int(m.group(2)), m.group(3)))
    return entries


def write_boundary_ids(mesh_fn, out_fn):
    """Parse a mesh's $PhysicalNames and write {calving, other} ids to out_fn.

    Importable so the mesh pipeline can emit a sidecar that always matches the
    mesh it just wrote. Returns the {"calving": [...], "other": [...]} dict.
    """
    print(f"Reading physical groups from {mesh_fn}")
    entries = parse_physical_names(mesh_fn)
    if not entries:
        raise ValueError(
            f"No $PhysicalNames block found in {mesh_fn}. "
            "Was the mesh generated by mesh_antarctica.py?"
        )

    calving, other, skipped = [], [], []
    for dim, tag, name in entries:
        if dim != 1:
            continue  # surfaces ("Ice") and any interior curves are not BCs
        if name.startswith("Calving"):
            calving.append(tag)
        elif name.startswith("Other"):
            other.append(tag)
        else:
            skipped.append((tag, name))

    if skipped:
        print(f"  Warning: {len(skipped)} unrecognized boundary group(s): "
              f"{skipped[:5]}{' ...' if len(skipped) > 5 else ''}")

    bnd_ids = {"calving": sorted(calving), "other": sorted(other)}
    with open(out_fn, "w") as f:
        json.dump(bnd_ids, f, indent=2)
    print(f"  {len(calving)} calving + {len(other)} other boundaries")
    print(f"Wrote {out_fn}")
    return bnd_ids


def main():
    mesh_fn = os.environ.get(
        "ISMIP7_MESH", os.path.join(MESH_DIR, f"antarctica_{lc_coarse}_{lc}.msh")
    )
    out_fn = os.environ.get("ISMIP7_BNDIDS")
    if out_fn:
        write_boundary_ids(mesh_fn, out_fn)
        return
    # Both names: the per-mesh sidecar the solvers prefer (which the next mesh
    # build cannot invalidate) and the shared fallback.
    stem = os.path.splitext(os.path.basename(mesh_fn))[0]
    write_boundary_ids(mesh_fn, os.path.join(MESH_DIR, f"boundary_ids_{stem}.json"))
    write_boundary_ids(mesh_fn, os.path.join(MESH_DIR, "boundary_ids.json"))


if __name__ == "__main__":
    main()
